Allow a full deployment not called 'prod' for pex deploys
dagster-io/dagster-cloud-action pull request #155
Opened 2023-10-10 16:31 UTC by shalabhc

The default deployment name can be overridden using the `deployment:` input to the action. Eg

<img width="620" alt="image" src="https://github.com/dagster-io/dagster-cloud-action/assets/7066873/d21ee1e3-0aeb-4a99-b087-d986f79a82f7">

## Test Plan
Rename a deployment to something other than `prod`
Point the `build_deploy_python_executable` action in `deploy.yml` to this branch and add the `deployment:` input
Verify that the workflow deployment works
Rename deployment back to `prod`
Verify that workflow deployment fails
Remove `deployment:` input
Verify that the workflow deployment works again

Ran all above steps in a test org successfully.

2023-10-10 16:38 UTC, gibsondan commented
How suspicious is the test failure here?

2023-10-10 16:46 UTC, johannkm commented
This is different from how you set it for hybrid deploys right? Could we make both use this env var?

2023-10-11 14:50 UTC, gibsondan reviewed
It's also different than how you set it for Docker deploys within serverless, agree that consistency would be ideal here:

https://github.com/dagster-io/dagster-cloud-action/blob/main/actions/serverless_prod_deploy/action.yml#L19-L22

We should also set this automatically when a new github action is created automatically from Dagster Cloud and the deployment isn't prod

2023-10-11 14:50 UTC, gibsondan requested changes
see inline

2023-10-12 00:00 UTC, shalabhc commented
ah good points re consistency. I'll make this self consistent with how we do serverless docker deploys using the input field instead.

eventually i want to replace the serverless workflow entirely with the new workflows we use for hybrid (https://github.com/dagster-io/dagster-cloud-hybrid-quickstart/) but haven't gotten around to testing, releasing and documenting that.

2023-10-13 18:33 UTC, shalabhc commented
@gibsondan - made this consistent with docker deploys using a new `deployment:` input. Tested manually successfully:
<img width="462" alt="image" src="https://github.com/dagster-io/dagster-cloud-action/assets/7066873/7c917aef-c3a9-41bd-9a02-12b9603c6902">
<img width="1322" alt="image" src="https://github.com/dagster-io/dagster-cloud-action/assets/7066873/c71cbc93-b530-4124-99fa-d5d8d5d48888">


The test failures have been happening for a while and we haven't gotten around to identifying or fixing them yet.

2023-10-13 18:38 UTC, gibsondan approved these changes
thanks - can you fill in the test plan? probably something like 'make a new serverless deployment that isn't prod, update the deploy.yml, it deploys to the correct place?'

2023-10-13 18:38 UTC, gibsondan commented on src/deploy_pex.py
> +        print(f"Deploying to a full deployment: {deployment_name}", flush=True)
"Deploying to a deployment" reads a bit oddly

2023-10-13 18:48 UTC, merged