[deploy] Add ability to customize location load timeout
dagster-io/dagster-cloud-action pull request #72
Opened 2022-12-09 17:39 UTC by benpankow

## Summary

Adds an optional `location_load_timeout` param which lets a user override the default code location load timeout (10m).

2022-12-09 17:39 UTC, benpankow commented
Current dependencies on/for this PR:
* main
  * **PR #72** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster-cloud-action/72" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster-cloud-action/72?utm_source=stack-comment).

2022-12-09 17:41 UTC, gibsondan approved these changes

2022-12-09 17:41 UTC, gibsondan commented on actions/utils/deploy/action.yml
> +  location_load_timeout:
maybe deploy_timeout? The timeout it will wait for it be deployed by dagster cloud?

2023-04-18 19:53 UTC, prha requested changes
need to rebase, rerequest

2024-12-10 19:31 UTC, closed without merging